name: Python application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  schedule:
    - cron: "0 6,18 * * *"

permissions:
  contents: read

jobs:
  build:
    permissions: write-all

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov black isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Format with black
      run: |
        black --check .

    - name: Sort imports with isort
      run: |
        isort --check --profile=black .

    - name: Test with pytest
      run: |
        pytest